/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocationRouteImport } from './routes/$location'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationIndexRouteImport } from './routes/$location.index'
import { Route as LocationOverviewRouteImport } from './routes/$location.overview'
import { Route as LocationHistoryRouteImport } from './routes/$location.history'
import { Route as LocationBrowseRouteImport } from './routes/$location.browse'
import { Route as LocationModelsIdRouteImport } from './routes/$location.models.$id'

const LocationRoute = LocationRouteImport.update({
  id: '/$location',
  path: '/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationRoute,
} as any)
const LocationOverviewRoute = LocationOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LocationRoute,
} as any)
const LocationHistoryRoute = LocationHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LocationRoute,
} as any)
const LocationBrowseRoute = LocationBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => LocationRoute,
} as any)
const LocationModelsIdRoute = LocationModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => LocationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$location': typeof LocationRouteWithChildren
  '/$location/browse': typeof LocationBrowseRoute
  '/$location/history': typeof LocationHistoryRoute
  '/$location/overview': typeof LocationOverviewRoute
  '/$location/': typeof LocationIndexRoute
  '/$location/models/$id': typeof LocationModelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$location/browse': typeof LocationBrowseRoute
  '/$location/history': typeof LocationHistoryRoute
  '/$location/overview': typeof LocationOverviewRoute
  '/$location': typeof LocationIndexRoute
  '/$location/models/$id': typeof LocationModelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$location': typeof LocationRouteWithChildren
  '/$location/browse': typeof LocationBrowseRoute
  '/$location/history': typeof LocationHistoryRoute
  '/$location/overview': typeof LocationOverviewRoute
  '/$location/': typeof LocationIndexRoute
  '/$location/models/$id': typeof LocationModelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$location'
    | '/$location/browse'
    | '/$location/history'
    | '/$location/overview'
    | '/$location/'
    | '/$location/models/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$location/browse'
    | '/$location/history'
    | '/$location/overview'
    | '/$location'
    | '/$location/models/$id'
  id:
    | '__root__'
    | '/'
    | '/$location'
    | '/$location/browse'
    | '/$location/history'
    | '/$location/overview'
    | '/$location/'
    | '/$location/models/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationRoute: typeof LocationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$location': {
      id: '/$location'
      path: '/$location'
      fullPath: '/$location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$location/': {
      id: '/$location/'
      path: '/'
      fullPath: '/$location/'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof LocationRoute
    }
    '/$location/overview': {
      id: '/$location/overview'
      path: '/overview'
      fullPath: '/$location/overview'
      preLoaderRoute: typeof LocationOverviewRouteImport
      parentRoute: typeof LocationRoute
    }
    '/$location/history': {
      id: '/$location/history'
      path: '/history'
      fullPath: '/$location/history'
      preLoaderRoute: typeof LocationHistoryRouteImport
      parentRoute: typeof LocationRoute
    }
    '/$location/browse': {
      id: '/$location/browse'
      path: '/browse'
      fullPath: '/$location/browse'
      preLoaderRoute: typeof LocationBrowseRouteImport
      parentRoute: typeof LocationRoute
    }
    '/$location/models/$id': {
      id: '/$location/models/$id'
      path: '/models/$id'
      fullPath: '/$location/models/$id'
      preLoaderRoute: typeof LocationModelsIdRouteImport
      parentRoute: typeof LocationRoute
    }
  }
}

interface LocationRouteChildren {
  LocationBrowseRoute: typeof LocationBrowseRoute
  LocationHistoryRoute: typeof LocationHistoryRoute
  LocationOverviewRoute: typeof LocationOverviewRoute
  LocationIndexRoute: typeof LocationIndexRoute
  LocationModelsIdRoute: typeof LocationModelsIdRoute
}

const LocationRouteChildren: LocationRouteChildren = {
  LocationBrowseRoute: LocationBrowseRoute,
  LocationHistoryRoute: LocationHistoryRoute,
  LocationOverviewRoute: LocationOverviewRoute,
  LocationIndexRoute: LocationIndexRoute,
  LocationModelsIdRoute: LocationModelsIdRoute,
}

const LocationRouteWithChildren = LocationRoute._addFileChildren(
  LocationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationRoute: LocationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
